CREATE DATABASE Aug18
USE Aug18

CREATE TABLE test1 (id INT NOT NULL UNIQUE , fname VARCHAR(50),lname VARCHAR(50), indexname INT );
SELECT * FROM test1;
INSERT INTO test1 VALUES (1,'shashank','juneja',454),(2,'abc','xyz',45),(3,'pqr','df',4);
SELECT * FROM test1;
ALTER TABLE test1 ADD dob DATE;
UPDATE test1 SET dob='2014/02/05' WHERE id=1;
ALTER TABLE test1 DROP indexname;
ALTER TABLE test ADD PRIMARY KEY(id) 

CREATE TABLE test2 (id INT NOT NULL UNIQUE AUTO_INCREMENT , fname VARCHAR(50),lname VARCHAR(50), indexname INT );
SELECT * FROM test2;
INSERT INTO test2(fname,lname,indexname) VALUES ('shashank','juneja',454);
INSERT INTO test2(fname,lname,indexname) VALUES ('aSAs','sadsad',4554);

ALTER TABLE test2 AUTO_INCREMENT=5;

INSERT INTO test2(fname,lname,indexname) VALUES ('a4SAs','sadhsad',45554);
SELECT *FROM test2;

CREATE TABLE RESOURCE(id INT , NAME VARCHAR(500),Date_Of_Joining DATE , 
Years_Of_Exp INT , Yash_EmpID VARCHAR(500)); -- q1 

INSERT INTO RESOURCE (id,NAME,Date_Of_Joining,Years_Of_Exp,Yash_EmpID) 
VALUES(1,'Deepak batra','2014/01/20'	,1,'1002899'), 
(2,'Aadesh jain','2012/10/09',10,'1001553'),
(3,'Aafaque khan','2008/03/28',2,'1000193 '),
(4,'Aakash jain','2015/03/09',3,'1003719'),
(5,'Aamer ved','2015/03/26',4,'1003813'),
(6,'Aarti patankar','2014/12/01',8,'1003549'),
(7,'Aashish maheshwari','2014/03/13',6,'1003054'),
(8,'Aashutosh soni','2014/05/19',7,'1003177'),
(9,'Aasish sinha','2012/05/25',5,'1001285'),
(10,'Aayaz khan','2015/04/27',2,'1003927');  --q2

SELECT * FROM RESOURCE;

UPDATE RESOURCE SET Years_Of_Exp=8 WHERE Years_Of_Exp=10; -- q3 

DELETE FROM RESOURCE WHERE id = 10 ; --q4 

ALTER TABLE RESOURCE ADD  location VARCHAR(50); --q5

ALTER TABLE RESOURCE ADD CONSTRAINT PRIMARY KEY(id); --q6

INSERT INTO RESOURCE (id,NAME) VALUES (5,'abcd'); // checking FOR PRIMARY key...

ALTER TABLE RESOURCE MODIFY COLUMN id BIGINT; -- q7

SELECT * FROM RESOURCE;  --q8

SELECT * FROM RESOURCE ORDER BY Date_Of_Joining;

SELECT * FROM RESOURCE ORDER BY Date_Of_Joining DESC;  --q9

SELECT * FROM RESOURCE ORDER BY NAME;  --q10

SELECT NAME,Yash_EmpID FROM RESOURCE WHERE Years_Of_Exp = 
(SELECT MAX(Years_OF_Exp) FROM RESOURCE); --q11


ALTER TABLE RESOURCE DROP COLUMN Years_Of_Exp;  --q12

ALTER TABLE RESOURCE DROP location;

ALTER TABLE RESOURCE ADD COLUMN location VARCHAR(50);



CREATE TABLE EMPLOYEE_SALARY(id INT ,EMP_ID VARCHAR(50) ,EMP_SALARY INT ); --q13

INSERT INTO EMPLOYEE_SALARY(id,emp_id) SELECT id,Yash_empID FROM resource; 
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 1100 WHERE id = 1 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 2015 WHERE id = 2 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 4655 WHERE id = 3 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 7845 WHERE id = 4 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 5265 WHERE id = 5 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 1009 WHERE id = 6 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 1555 WHERE id = 7 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 1121 WHERE id = 8 ;
UPDATE EMPLOYEE_SALARY SET EMP_SALARY = 1555 WHERE id = 9 ; --q14 

SELECT * FROM EMPLOYEE_SALARY;

ALTER TABLE EMPLOYEE_SALARY ADD PRIMARY KEY(EMP_ID);    

ALTER TABLE resource MODIFY COLUMN ID INT;

ALTER TABLE EMPLOYEE_SALARY ADD CONSTRAINT fk_q FOREIGN KEY(ID) REFERENCES RESOURCE(id) ON DELETE CASCADE;  --q16

ALTER TABLE EMPLOYEE_SALARY DROP FOREIGN KEY employee_salary_ibfk_1;


SELECT * FROM EMPLOYEE_SALARY;
SELECT * FROM RESOURCE;

INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (100) WHERE id = 1;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (200) WHERE id = 2;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (300) WHERE id = 3;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (900) WHERE id = 4;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (800) WHERE id = 5;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (700) WHERE id = 6;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (600) WHERE id = 7;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (500) WHERE id = 8;
INSERT INTO EMPLOYEE_SALARY (EMP_SALARY) VALUES (150) WHERE id = 9;


SELECT NAME,Yash_EmpID FROM RESOURCE WHERE id = 
(SELECT id FROM EMPLOYEE_SALARY WHERE EMP_SALARY=(SELECT MAX(EMP_SALARY) FROM EMPLOYEE_SALARY)); --q17

(SELECT id,EMP_SALARY FROM  EMPLOYEE_SALARY ORDER BY EMP_SALARY DESC LIMIT 3);


SELECT r.Yash_EmpID , r.NAME, e.EMP_SALARY 
FROM RESOURCE AS r  , EMPLOYEE_SALARY AS e WHERE r.id = e.id ORDER BY EMP_SALARY DESC LIMIT 3;  --q18

	